import { useEffect, useState } from 'react';
import { captureSharedWorkspace, loadSharedWorkspace, restoreSharedVersion, WORKSPACE_EVENT } from '../../services/workspaceSync';
const labels: Record<string, string> = { nav_cms_draft: '导航内容与布局', nav_temp_text: '临时文本', nav_click_stats_v2: '访问统计', nav_translation_history: '翻译历史', nav_temporary_url_visits_v1: '临时访问', scene_mode: '场景模式', theme: '主题' };
export function SharedVersions() {
  const [store, setStore] = useState(() => loadSharedWorkspace());
  const [message, setMessage] = useState('');
  useEffect(() => { const refresh = () => { try { setStore(captureSharedWorkspace()); } catch { setMessage('本机存储失败，请保持页面打开并备份。'); } }; window.addEventListener(WORKSPACE_EVENT, refresh); const timer = setInterval(refresh, 2000); return () => { clearInterval(timer); window.removeEventListener(WORKSPACE_EVENT, refresh); }; }, []);
  return <details className="rounded-xl bg-[#5f8f84]/5 p-3 text-xs"><summary className="cursor-pointer">设置与历史副本（{Object.values(store.history).reduce((sum, values) => sum + values.length, 0)}）</summary><p className="mt-2">设置按项采用较新版本，最近 5 个不同版本可恢复；阅读记录按文章合并。恢复副本后需再次同步。</p>{Object.entries(store.history).map(([key, entries]) => <details key={key} className="mt-3"><summary>{labels[key] || key}</summary>{entries.map((entry, i) => <div className="mt-2 rounded-lg border border-[#5f8f84]/20 p-2" key={`${entry.updatedAt}-${i}`}><time>{new Date(entry.updatedAt).toLocaleString('zh-CN')}</time><pre className="mt-1 max-h-24 overflow-auto whitespace-pre-wrap break-all">{entry.value?.slice(0, 300) || '（空值）'}{(entry.value?.length || 0) > 300 ? '…' : ''}</pre><button type="button" className="baize-button-secondary mt-2" onClick={() => { if (!window.confirm(`确认恢复“${labels[key] || key}”的这个版本？当前内容仍会保留为历史副本。`)) return; try { restoreSharedVersion(key, entry); setMessage('已恢复到本机，请再次同步。'); } catch (error) { setMessage((error as Error).message); } }}>恢复此副本</button></div>)}</details>)}<p role="status">{message}</p></details>;
}
