/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-gradient-to-br',
    'bg-gradient-to-b',
    'from-blue-50',
    'via-indigo-50',
    'to-purple-50',
    'to-indigo-50',
    'from-white/80',
    'to-blue-50/50',
    'to-indigo-50/50',
    'dark:from-gray-900',
    'dark:via-slate-900',
    'dark:to-gray-800',
    'from-indigo-50',
    'to-purple-50',
    'dark:to-slate-900',
    'from-slate-900',
    'via-indigo-950',
    'to-slate-900',
    'dark:from-gray-950',
    'dark:to-black',
    'dark:from-gray-900/80',
    'dark:to-slate-900/50',
    'dark:to-indigo-950/50',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  darkMode: 'class',
}
