import { useMemo, useState } from 'react';
import { X } from 'lucide-react';
import type { TextIndex } from '../types/text-network';
import { selectTextGraph } from '../services/textGraph';
const labels: Record<string, string> = { post: '文章', topic: '主题', project: '项目', note: '笔记', site: '网站' };
const colors: Record<string, string> = { post: '#356b66', topic: '#a07b30', project: '#5b6ba3', note: '#935879', site: '#597177' };
export function TextGraphPanel({ index, onClose }: { index: TextIndex; onClose: () => void }) {
  const [topicId, setTopicId] = useState(''), [focusId, setFocusId] = useState(''), [oneHop, setOneHop] = useState(false), [type, setType] = useState(''), [recentDays, setRecentDays] = useState(0);
  const graph = useMemo(() => selectTextGraph(index, { topicId, focusId, oneHop, type, recentDays }), [index, topicId, focusId, oneHop, type, recentDays]);
  const positions = new Map(graph.nodes.map((node, i) => { const angle = i * Math.PI * 2 / Math.max(graph.nodes.length, 1) - Math.PI / 2; const radius = node.type === 'topic' ? 150 : 255; return [node.id, { x: 400 + Math.cos(angle) * radius, y: 330 + Math.sin(angle) * radius }]; }));
  const focused = index.nodes.find(node => node.id === focusId);
  return <section className="baize-panel min-w-0 max-w-full scroll-mt-24 basis-full space-y-4 rounded-2xl p-4 sm:p-5" aria-label="知识关系图谱">
    <div className="flex items-center"><h2 className="flex-1 text-lg font-bold">知识关系图谱</h2><button type="button" className="baize-icon-button" onClick={onClose} aria-label="关闭图谱"><X size={18} /></button></div>
    <p className="text-xs leading-5">只使用博客公开索引，不上传或展示私有 Inbox。点击节点查看连接，再打开原文；侧边列表同样支持键盘操作。</p>
    <div className="grid gap-3 sm:grid-cols-3"><label className="text-xs">主题范围<select className="baize-input mt-1" value={topicId} onChange={event => setTopicId(event.target.value)}><option value="">全部主题</option>{index.nodes.filter(node => node.type === 'topic').map(node => <option key={node.id} value={node.id}>{node.title}</option>)}</select></label><label className="text-xs">节点类型<select className="baize-input mt-1" value={type} onChange={event => setType(event.target.value)}><option value="">全部类型</option>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="text-xs">更新范围<select className="baize-input mt-1" value={recentDays} onChange={event => setRecentDays(Number(event.target.value))}><option value={0}>全部时间</option><option value={7}>最近 7 天</option><option value={30}>最近 30 天</option><option value={90}>最近 90 天</option></select></label></div>
    <div className="flex flex-wrap items-center gap-4 text-xs"><label className="flex items-center gap-2"><input type="checkbox" checked={oneHop} disabled={!focusId} onChange={event => setOneHop(event.target.checked)} />只看所选节点及直接连接</label><button type="button" className="baize-button-secondary" onClick={() => { setTopicId(''); setFocusId(''); setOneHop(false); setType(''); setRecentDays(0); }}>重置筛选</button><span>{graph.nodes.length} 个节点 · {graph.edges.length} 条关系{graph.total > 300 ? '（最多展示 300 个，请缩小筛选范围）' : ''}</span></div>
    {focused && <div className="rounded-xl bg-[#5f8f84]/10 p-3"><strong>{focused.title}</strong><p className="mt-1 text-xs">{focused.summary}</p><a href={focused.url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm underline">打开{labels[focused.type] || '节点'} ↗</a></div>}
    {!graph.nodes.length ? <p className="py-8 text-center text-sm">当前筛选下没有节点。索引暂时不可用时，请联网刷新或使用已缓存内容。</p> : <div className="grid min-w-0 gap-4 lg:grid-cols-[minmax(0,1fr)_15rem]"><div className="min-w-0 overflow-x-auto rounded-xl bg-white/30 dark:bg-black/10"><svg viewBox="0 0 800 660" className="w-full min-w-[620px]" role="img" aria-label="文章与主题关系图"><title>点击节点查看详情，侧边列表提供等效操作</title>{graph.edges.map(edge => { const a = positions.get(edge.from)!, b = positions.get(edge.to)!; return <line key={`${edge.type}:${edge.from}:${edge.to}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={edge.type === 'topic' ? '#a07b30' : '#79958f'} strokeWidth={edge.from === focusId || edge.to === focusId ? 3 : 1} opacity={0.5} />; })}{graph.nodes.map(node => { const point = positions.get(node.id)!; return <g key={node.id} role="button" tabIndex={0} aria-label={`${labels[node.type]}：${node.title}`} onClick={() => setFocusId(node.id)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setFocusId(node.id); } }} className="cursor-pointer outline-none focus:opacity-60"><title>{node.title}</title><circle cx={point.x} cy={point.y} r={node.id === focusId ? 19 : node.type === 'topic' ? 15 : 11} fill={colors[node.type]} stroke="#edf2eb" strokeWidth={3} /><text x={point.x} y={point.y + 33} textAnchor="middle" fontSize={11} fill="currentColor">{node.title.slice(0, 15)}{node.title.length > 15 ? '…' : ''}</text></g>; })}</svg></div><div className="max-h-[38rem] space-y-2 overflow-y-auto" aria-label="图谱节点列表">{graph.nodes.map(node => <button key={node.id} type="button" className={`block w-full rounded-xl border p-3 text-left text-xs ${focusId === node.id ? 'border-[#356b66] bg-[#5f8f84]/15' : 'border-[#5f8f84]/15'}`} onClick={() => setFocusId(node.id)}><span className="mr-2" style={{ color: colors[node.type] }}>{labels[node.type]}</span>{node.title}</button>)}</div></div>}
  </section>;
}
