import { rotationCalendar } from './rotations.js?v=0.15.0';
import { specialtyPanel, bondsPanel } from './strategy-ui.js?v=0.15.0';
import { doctrinePanel } from './frontier-ui.js?v=0.15.0';
import { CORPS, CORPS_PROFILES, corpsRank, corpsQuote, targetQuote, presetReason } from './development.js?v=0.15.0';
import { ARMS } from './martial.js?v=0.15.0';
import { EQUIPMENT_SETS, equippedSets } from './equipment-sets.js?v=0.15.0';
const names={silver:'碎银',wood:'木材',food:'粮草'};
const busy=s=>!!(s.battle||s.scheme||s.event);
export function corpsPanel(s,d,h,btn){
  const c=CORPS[h.id],q=corpsQuote(s,h.id),owned=s.heroes[h.id].status==='owned';
  return `<section class="corps-panel"><p class="kicker">专属部队 · 随将出征</p><h3>${c.name}<span class="badge">${ARMS[c.arm].name} · ${q.rank} 阶</span></h3><p>${CORPS_PROFILES[c.profile].name}：${CORPS_PROFILES[c.profile].text}</p>${doctrinePanel(h)}${specialtyPanel(s,d,h,btn)}<p class="note">${owned?'英雄带兵时，乡勇按阵容顺序均分到各部；不足一人不触发部队效果。':'迎入寨中即可统领本部乡勇。'}独行时使用英雄自身专长。部队名称为本作设定。</p>${owned&&q.rank<3?`<p class="meta">升至 ${q.rank+1} 阶：碎银 ${q.cost.silver} · ${Object.entries(q.cost.items).map(([id,n])=>d.by.items[id].name+' '+(s.inventory[id]||0)+'/'+n).join(' · ')}</p><p class="note">${q.reason||'可以练兵，必定提升一阶。'}</p><div class="actions">${btn('训练专属部队',{type:'corpsTrain',id:h.id},'primary',!!q.reason)}${btn('追踪练兵材料',{type:'goalSet',kind:'corps',id:h.id},'secondary',busy(s))}</div>`:owned?'<p class="note">精锐三阶，已完成本部练兵。</p>':''}</section>`;
}
export function corpsLine(s,d){const total=s.camp?.mode==='army'?Math.min(s.camp.troops,s.camp.deployment):0;return `<div class="corps-line">${s.team.map((id,i)=>{const c=CORPS[id],n=Math.floor(total/s.team.length)+(i<total%s.team.length?1:0);return `<div><b>${d.by.heroes[id].name} · ${c.name}</b><span>${ARMS[c.arm].name} · ${corpsRank(s,id)}阶 · ${n} 人</span></div>`;}).join('')}</div>`;}
export function presetsPanel(s,d,btn){if(!s.camp)return '';return bondsPanel(s,d)+`<details class="fold-section" data-fold="formation-presets"><summary>阵容预设 · 三套英雄与军令</summary><p class="note">先保存上方阵容或出征配置，再记录预设。切换不招募、不治疗，也不消耗资源。</p><div class="preset-grid">${[1,2,3].map(slot=>{const p=s.development?.presets[slot],reason=presetReason(s,slot);return `<article class="card"><h3>阵容 ${slot}</h3><p>${p?p.team.map(id=>d.by.heroes[id].name).join(' · '):'尚未保存'}</p>${p?`<p class="note">${p.mode==='army'?'带兵 '+p.deployment+' 人':'英雄独行'} · ${{balanced:'稳扎稳打',assault:'强攻破阵',guard:'结阵固守'}[p.tactic]}</p>`:''}<div class="actions">${btn(p?'更新为当前配置':'记录当前配置',{type:'presetSave',slot},'secondary',!s.team.length||busy(s))}${btn('启用',{type:'presetLoad',slot},'primary',!!reason)}</div>${p&&reason?`<p class="note">${reason}</p>`:''}</article>`;}).join('')}</div></details>`;}
export function materialSource(id){return ({iron:'矿场：周一 / 四 / 日；铁匠铺采买或碎铁重熔',cloth:'矿场：周一 / 四 / 日；行囊采买',scrap_iron:'矿场：周一 / 四 / 日；分解闲置装备',martial_pages:'演武场：周二 / 五 / 日；寨子出征',spirit_essence:'灵蕴试炼；本期周本首通',immortal_seal:'登仙试炼；本期周本首通',mount_feed:'牧场：周三 / 六 / 日',mount_token:'牧场：周三 / 六 / 日；周本首通',exp_pill:'演武场：周二 / 五 / 日；行囊采买'})[id]||'江湖历练与行囊物品说明';}
export function targetPanel(s,d,btn){const q=targetQuote(s,d);if(!q)return '';return `<section class="material-target"><div class="section-top"><h2>养成目标 · ${q.name}</h2>${btn('取消追踪',{type:'goalClear'},'text-action',busy(s))}</div>${q.cost?`<p class="note">碎银 ${s.player.silver} / ${q.cost.silver||0} · ${q.reason||'查看下方材料进度'}</p><div>${Object.entries(q.cost.items||{}).map(([id,n])=>`<p class="target-row ${(s.inventory[id]||0)>=n?'target-ready':''}"><b>${d.by.items[id].name} ${Math.min(s.inventory[id]||0,n)} / ${n}</b><span>${materialSource(id)}</span>${['iron','cloth','scrap_iron','martial_pages','exp_pill','mount_feed','mount_token','spirit_essence','immortal_seal'].includes(id)?btn('查看获取副本',{type:'ui_materialSource',kind:['spirit_essence','immortal_seal'].includes(id)?'weekly':'daily',id:['spirit_essence','immortal_seal'].includes(id)?rotationCalendar(s.clock).route.id:['iron','cloth','scrap_iron'].includes(id)?'ore':['martial_pages','exp_pill'].includes(id)?'manual':'stable'},'text-action'):''}</p>`).join('')}</div>`:'<p>此目标已完成。</p>'}<div class="actions">${btn('前往养成',{type:'ui_goalOpen'},'secondary')}<button type="button" class="text-action" data-view="trials">查看材料日历</button></div></section>`;}
export function ledgerPanel(s,d){const rows=s.development?.ledger||[];return `<details class="fold-section" data-fold="daily-ledger"><summary>每日小结 · 收获与开支</summary><p class="note">按北京时间记录本次更新后的实际操作；保留最近两个有操作的日期。收获与开支按每次操作的资源净变化统计，不把读档当收获。</p>${[...rows].reverse().map(r=>`<article class="card"><h3>${r.date}</h3><p>胜利 ${r.wins} · 收兵 / 败退 ${r.losses} · 招贤 ${r.recruits}</p>${[['gained','带回'],['spent','支出']].map(([k,label])=>`<p class="note"><b>${label}：</b>${Object.entries(r[k]).map(([id,n])=>(names[id]||d.by.items[id].name)+' ×'+n).join('、')||'暂无'}</p>`).join('')}</article>`).join('')||'<p class="note">办理一次寨务后，记录便从这里开始。</p>'}</details>`;}
export function setPanel(s,d,id){return `<details class="fold-section" data-fold="hero-sets-${id}"><summary>装备套装 · 两件起效</summary>${equippedSets(s,id).filter(x=>x.count).map(x=>`<p><b>${x.name} ${x.count} / 3</b> · ${x.text}${x.count<2?'（尚未激活）':''}</p>`).join('')||'<p class="note">暂未穿戴套装部件。</p>'}<button class="text-action" type="button" data-view="forge">查看套装与打造</button></details>`;}
export function setsCatalog(s,d,btn){return `<section class="location"><h2>套装搭配</h2><p class="note">同一位好汉穿戴两件起效，三件追加效果；强化等级不影响件数。角色属性已计入已激活套装。</p><div class="preset-grid">${EQUIPMENT_SETS.map(set=>`<article class="card"><h3>${set.name}</h3><p>${set.text}</p>${set.items.map(id=>`<div class="set-piece"><span>${d.by.equipments[id].name}</span>${btn('追踪打造材料',{type:'goalSet',kind:'craft',id},'text-action',busy(s))}</div>`).join('')}</article>`).join('')}</div><h3>碎铁回炉</h3><p class="note">分解与矿场所得碎铁，可用于专属练兵，也能重熔为强化所需精铁。</p>${btn('碎铁 5 + 碎银 20 → 精铁 2',{type:'scrapSmelt'},'secondary',(s.inventory.scrap_iron||0)<5||s.player.silver<20||busy(s))}</section>`;}
export function qualityTechnique(h){const effects={fighter:'进阶招式追加流血：灵品 4 秒，仙品 6 秒。',defender:'进阶招式追加护阵 4 秒：灵品保护最低血量同伴（减伤 15%），仙品保护全队（减伤 25%）。',ranger:'进阶招式后追射最低血量敌人：灵品 35%、仙品 70% 攻击倍率。',strategist:'进阶招式额外削减敌军怒气：灵品前一人 10 点，仙品前两人各 15 点。',support:'进阶招式后为最低血量同伴清除一项负面状态，并恢复最大气血的 5% / 10%。'};return `<p class="note"><b>升品变招：</b>${effects[h.type]}建寨后非剧情战生效，须先解锁人物进阶招式。</p>`;}
