import {specialDropTable,SPECIAL_DUNGEONS} from './special-dungeons-data.js?v=0.69.0';
import {requireRule} from './utils.js?v=0.69.0';
import {itemAction} from './item.js?v=0.69.0';
export function recordHunt(s,b){if(b.outcome!=='victory')return;const x=s.fieldwork??={version:1,hunts:{}};for(const row of specialDropTable(b.context.id,b.context.tier).filter(r=>r.kind==='equipment')){const old=x.hunts[row.id]||{runs:0,hits:0,dry:0},hit=s.specialDungeons.last.drops.some(r=>r.kind==='equipment'&&r.id===row.id&&r.stored>0);x.hunts[row.id]={runs:Math.min(10000000,old.runs+1),hits:Math.min(10000000,old.hits+(hit?1:0)),dry:hit?0:Math.min(10000000,old.dry+1)};}}
export function duplicateQuote(s,d){const keep=new Set(s.equipment.filter(e=>e.hero||e.locked||e.plus||e.refine||d.by.equipments[e.item].tier>=3).map(e=>e.item)),ids=[];let scrap=0;for(const e of s.equipment){if(e.hero||e.locked||e.plus||e.refine||d.by.equipments[e.item].tier>=3)continue;if(!keep.has(e.item)){keep.add(e.item);continue;}ids.push(e.uid);scrap+=d.by.equipments[e.item].tier*2;}return {ids,scrap};}
export function dismantleDuplicates(s,d,a){const q=duplicateQuote(s,d);requireRule(q.ids.length&&JSON.stringify(a.ids)===JSON.stringify(q.ids),'装备已变化，请重新预览整理。');requireRule((s.inventory.scrap_iron||0)+q.scrap<=10000000,'碎铁已达上限。');for(const id of q.ids)itemAction(s,d,{type:'dismantle',id});}
export function farmStop(s,d,session){if(s.battle)return '';if(s.specialDungeons?.last?.outcome!=='victory')return '本战未胜，已停止连续挑战。';if(session.done>=session.count)return '已完成约定场数。';if(s.equipment.length>=190)return '装备接近满格，先整理行囊。';if((s.inventory.jinchuangyao||0)<session.medicine)return '药品少于设定的保留数量。';const drops=s.specialDungeons?.last?.drops||[];if(drops.some(r=>r.stored>0&&(r.kind==='equipment'&&d.by.equipments[r.id].tier>=3||r.kind==='item'&&['recruit_order','spirit_essence','immortal_seal','blueprint','mount_token'].includes(r.id))))return '得到珍稀物品，已停下供你查看。';return '';}
export function validateFieldwork(s,d,check){const x=s.fieldwork;if(x===undefined)return;check(x&&x.version===1&&Object.keys(x).length===2&&x.hunts&&typeof x.hunts==='object'&&!Array.isArray(x.hunts),'刷取记录');const num=n=>Number.isSafeInteger(n)&&n>=0&&n<=10000000;for(const [id,r]of Object.entries(x.hunts))check(!!d.by.equipments[id]&&Object.keys(SPECIAL_DUNGEONS).some(k=>[1,2,3].some(t=>specialDropTable(k,t).some(v=>v.kind==='equipment'&&v.id===id)))&&r&&Object.keys(r).sort().join(',')==='dry,hits,runs'&&num(r.runs)&&num(r.hits)&&num(r.dry)&&r.hits<=r.runs&&r.dry<=r.runs-r.hits,'装备掉落记录');}
export function fieldworkPreserved(a,b){return !a.fieldwork||!!b.fieldwork&&Object.entries(a.fieldwork.hunts).every(([id,r])=>(b.fieldwork.hunts[id]?.runs??-1)>=r.runs&&(b.fieldwork.hunts[id]?.hits??-1)>=r.hits);}
export const hasFieldwork=s=>!!s.fieldwork||!!s.adventure?.run?.events||[s.battle,s.lastBattle].some(b=>['ambush','attrition'].includes(b?.context?.challenge))||Object.keys(s.replays?.challenges||{}).some(k=>/_2_(ambush|attrition)$/.test(k));
