import {trackedGoalStrip} from './tactics-ui.js?v=0.58.0';
import {isExternal,isWanderer} from './roster.js?v=0.58.0';
import {HERO_ROLES} from './hero-roles.js?v=0.58.0';
import {attributes} from './hero.js?v=0.58.0';
import {experienceToNext,ATTRIBUTE_NAMES} from './progression.js?v=0.58.0';
import {qualityOf,QUALITIES} from './quality.js?v=0.58.0';
import {CORPS} from './corps-data.js?v=0.58.0';
import {storyObjective} from './story-guide.js?v=0.58.0';
import {journeyNextGoal} from './journey-goals-ui.js?v=0.58.0';
import {campNotices} from './camp-overview.js?v=0.58.0';
import {icon} from './icons.js?v=0.58.0';
const roles={fighter:'先锋',defender:'护阵',ranger:'游击',strategist:'谋士',support:'辅佐'};
export function campDashboard(s,d,esc,btn,more){const g=journeyNextGoal(s,d),story=storyObjective(s,d),notices=campNotices(s,d),links=[['营建','camp','buildings','forge'],['募兵医治','camp','troops','heroes'],['山寨出征','camp','raids','map'],['招贤','recruit','ordinary','recruit'],['打造','forge','craft','forge'],['资源副本','trials','resources','trials']];const lead=s.progress.flags.volume_six_complete?'<section class="folio-next" data-mainline aria-label="当前主线目标"><span class="folio-eyebrow">主线 · 第 '+story.chapter+' 卷 · '+story.done+'/'+story.total+'</span><h2>'+esc(story.title)+'</h2><p>'+esc(story.reason||story.detail)+'</p>'+btn(s.progress.flags.volume_twelve_complete?'查看结局与后记':'继续主线',{type:'ui_storyResume'},'primary')+'</section><section class="folio-story" aria-label="下一步游玩目标"><div><small>游历</small><strong>'+esc(g.title)+'</strong></div>'+btn(g.label||'前往',g.command,'secondary')+'</section>':'<section class="folio-next" aria-label="下一步游玩目标"><span class="folio-eyebrow">寨务</span><h2>'+esc(g.title)+'</h2><p>'+esc(g.text)+'</p>'+btn(g.label||'前往',g.command,'primary')+'</section><section class="folio-story" aria-label="当前主线目标"><div><small>主线 · 第 '+story.chapter+' 卷 · '+story.done+'/'+story.total+'</small><strong>'+esc(story.title)+'</strong></div>'+btn('继续主线',{type:'ui_storyResume'},'secondary')+'</section>';return '<div class="camp-dashboard">'+trackedGoalStrip(s,d,btn)+lead+'<nav class="folio-shortcuts" aria-label="常用寨务">'+links.map(([name,view,id,symbol])=>'<button type="button" class="secondary" data-command="'+esc(JSON.stringify({type:'ui_section',view,id}))+'">'+icon(symbol)+'<span>'+name+'</span></button>').join('')+'</nav><details class="folio-more" data-fold="camp-all-functions"><summary>全部寨务'+(notices.length?' · '+notices.length+' 项待办':'')+'</summary>'+(notices.length?'<div class="actions">'+notices.slice(0,3).map(n=>n.view?'<button type="button" class="secondary" data-view="'+n.view+'">'+esc(n.label)+'</button>':btn(n.label,{type:'ui_campJump',id:n.target},'secondary')).join('')+'</div>':'')+more+'</details></div>';}
export function heroDossier(s,d,h,esc,btn,portrait,invitation,requested='attributes'){
 const v=s.heroes[h.id],owned=v.status==='owned',a=owned?attributes(s,h.id,d):null,q=QUALITIES[qualityOf(v)],role=HERO_ROLES[h.id],full=v.level>=d.config.balance.heroLevelCap,tab=['attributes','ability','develop'].includes(requested)?requested:'attributes',identity=isWanderer(h)?'江湖散人 · 不占正册座次':isExternal(h)?'外传人物 · 不占正册座次':h.starSign+' · 第 '+h.seat+' 席';
 const away=s.affairs?.mission?.hero===h.id||s.realm?.squad?.team.includes(h.id);
 const attributesPanel=owned?'<section class="dossier-experience"><span>历练</span><b>'+(full?'已满级':v.exp+' / '+experienceToNext(v.level))+'</b>'+(!full?'<progress aria-label="人物升级经验" value="'+v.exp+'" max="'+experienceToNext(v.level)+'"></progress>':'')+'</section><dl class="dossier-stats">'+Object.entries(ATTRIBUTE_NAMES).map(([key,name])=>'<div><dt>'+name+'</dt><dd>'+a[key]+'</dd></div>').join('')+'</dl><p class="note dossier-stat-note">已含装备等加成；出征时另计兵力和军令。</p>':invitation(s,h,btn);
 const abilities='<section class="dossier-ability"><h3>'+esc(role.name)+'</h3><p>'+esc(role.text)+'</p><span class="note">专属兵种 · '+esc(CORPS[h.id]?.name||'待查')+'</span></section><div class="actions">'+btn('查看招式',{type:'ui_section',view:'heroes',id:'skills',hero:h.id},'secondary',!owned)+btn('兵种详情',{type:'ui_section',view:'heroes',id:'corps',hero:h.id},'secondary',!owned)+'</div>';
 const develop='<div class="dossier-actions">'+[['training','升级'],['skills','招式坐骑'],['corps','专属兵种'],['quality','品阶突破'],['talents','天赋装备'],['tasks','人物传记']].map(([id,name])=>btn(name,{type:'ui_section',view:'heroes',id,hero:h.id},id==='training'?'primary':'secondary',!owned)).join('')+'</div><details data-fold="dossier-history-'+h.id+'"><summary>人物往事</summary><p>'+esc(identity)+'</p><p>'+esc(h.story)+'</p></details>';
 return '<article class="hero-dossier"><header class="dossier-identity">'+portrait(h,true)+'<div><p class="meta">'+esc(h.title)+' · '+roles[h.type]+'</p><h2>'+esc(h.name)+' <span class="quality-badge quality-'+qualityOf(v)+'">'+q.name+'品</span></h2><span class="note">'+(owned?v.level+' 级 · '+(away?'外派中':s.team.includes(h.id)?'当前出阵':'寨中待命'):'尚未入寨')+' · '+h.star+' 星</span></div></header><nav class="dossier-tabs" aria-label="人物档案分区">'+[['attributes','属性'],['ability','本领'],['develop','养成']].map(([id,name])=>btn(name,{type:'ui_dossierTab',id},'secondary').replace('<button ','<button aria-current="'+(id===tab?'page':'false')+'" ')).join('')+'</nav><div class="dossier-panel" '+(tab!=='attributes'?'hidden':'')+'>'+attributesPanel+'</div><div class="dossier-panel" '+(tab!=='ability'?'hidden':'')+'>'+abilities+'</div><div class="dossier-panel" '+(tab!=='develop'?'hidden':'')+'>'+develop+'</div></article>';
}
