import {GRAIN_ROUTES,GRAIN_SCOUTS,GRAIN_INVESTMENTS,grainIncome,grainDelivery} from './grain-road-data.js?v=0.69.0';
import {grainQuote} from './grain-road.js?v=0.69.0';
export function grainRoadPanel(s,d,esc,btn,selected='escort'){
 if(!Object.hasOwn(GRAIN_ROUTES,selected))selected='escort';
 const x=s.grainRoad,q=grainDelivery(s),go=(label,view,id)=>btn(label,{type:'ui_section',view,id},'secondary');
 const recovery='<div class="actions">'+go('采集物资','camp','duties')+go('募兵医治','camp','troops')+go('培养好汉','heroes','training')+'</div>';
 const report=x?.last?'<p class="note">上次'+({victory:'得胜',defeat:'战败',retreat:'撤退'})[x.last.outcome]+'：随军 '+x.last.troops+'，伤兵 '+x.last.wounded+'，阵亡 '+x.last.fallen+'。'+(x.last.route==='escort'?'粮车剩余 '+x.last.cargo+'%。':'')+'</p>':'';
 if(x?.won){const m=GRAIN_ROUTES[x.route],hours=Math.max(1,Math.ceil((86400000-(s.clock-x.lastAt)%86400000)/3600000));return '<article class="grain-road-summary"><h2>粮路已通</h2><p>'+m.result+'</p>'+report+'<p><b>每日供粮 '+grainIncome(s)+'</b> · 最多积存 3 天</p><p>'+(q.days?'粮队已带回 '+q.food+' 粮草'+(q.healed?'，可接回 '+q.healed+' 名伤兵':''):'下批粮队约 '+hours+' 小时后到寨。')+'</p>'+(q.days?btn('收下粮草'+(q.healed?'并接回伤兵':''),{type:'grainRoadCollect'},'primary'):'')+'</article>'+(x.investment?'<article class="grain-road-summary"><h3>'+GRAIN_INVESTMENTS[x.investment].name+' · 已建成</h3><p>'+GRAIN_INVESTMENTS[x.investment].text+'</p></article>':'<section class="grain-road-investments"><h3>下一步修什么？</h3><p class="note">木材 30、碎银 60，二选一，建成后保留。建成时结清整日供粮，再重新计时。</p><div class="grain-road-choices">'+Object.entries(GRAIN_INVESTMENTS).map(([id,m])=>'<article><h3>'+m.name+'</h3><p>'+m.text+'</p>'+btn('建造',{type:'grainRoadInvest',id},'secondary',s.camp.wood<m.wood||s.player.silver<m.silver)+'</article>').join('')+'</div></section>')+recovery+btn('继续主线',{type:'ui_storyResume'},'secondary');}
 const scouts=Object.entries(s.heroes).filter(([id,h])=>h.status==='owned'&&s.affairs?.mission?.hero!==id&&!s.realm?.squad?.team.includes(id)).sort(([a],[b])=>Number(GRAIN_SCOUTS.includes(b))-Number(GRAIN_SCOUTS.includes(a)));
 return '<section class="grain-road-brief"><h2>打通粮路</h2><p>粮车被劫，商人不敢进山。选一种办法，替寨子打通粮路。</p>'+report+'</section><nav class="grain-route-tabs" aria-label="粮路方案">'+Object.entries(GRAIN_ROUTES).map(([id,m])=>btn(({escort:'护送',scout:'侦察',assault:'强攻'})[id],{type:'ui_grainRoute',id},'secondary').replace('<button ','<button aria-pressed="'+(id===selected)+'" ')).join('')+'</nav><p class="note">护送：粮 90–180，每日 24；侦察剿匪：粮 210，每日 18；强攻：粮 260，每日 12。只能打通一次。</p><div class="grain-road-choices">'+Object.entries(GRAIN_ROUTES).filter(([id])=>id===selected).map(([id,m])=>{const cost=grainQuote(s,id),scout=id==='scout';return '<article data-grain-route="'+id+'"><h3>'+m.name+'</h3><p>'+m.text+'</p><p class="meta">胜利粮草 '+(id==='escort'?'90–180（看粮车余量）':m.reward)+' · 此后每日 '+m.income+'</p>'+(id==='escort'?'<p class="note">粮车被毁即失败。固守军令或战中收势可减轻粮车受损。</p>':id==='assault'?'<p class="note">敌军更强；开战 15 秒内普攻伤害降低 35%，招式不受此限。</p>':'<p class="note">白胜、时迁、戴宗、解珍、解宝擅长探路：体力 2，敌军再弱 15%；其他好汉探路体力 4。</p>')+(scout?(x?.scout?'<p>已由 '+esc(d.by.heroes[x.scout].name)+' 探明侧路。</p>':'<label>派谁探路<select id="grain-scout">'+scouts.map(([hid])=>'<option value="'+hid+'">'+esc(d.by.heroes[hid].name)+(GRAIN_SCOUTS.includes(hid)?' · 体力 2':' · 体力 4')+'</option>').join('')+'</select></label>'+btn('派人探路',{type:'ui_grainScout'},'secondary',!scouts.length)):'')+'<p class="note">当前配置：随军 '+cost.troops+' 人，粮草 '+cost.food+'。'+esc(cost.reason)+'</p>'+btn('查看出征方案',{type:'grainRoadBattle',id},'primary',scout&&!x?.scout)+'</article>';}).join('')+'</div><p class="note">出征体力 6。失败可换路线，消耗与兵损不返还。可在出征准备中调整兵数、军令或改为独行；取消不扣出征物资。</p>'+recovery;
}
