import {accrueContacts} from './exploration.js?v=0.69.0';
import {REGION_CONTACTS} from './exploration-data.js?v=0.69.0';
import {knowHero} from './hero.js?v=0.69.0';
import {ensureGathering} from './gathering.js?v=0.69.0';
import {IDLE_ROUTES,IDLE_CYCLE,IDLE_CAP,idleUnlocked,idleRates,idleAvailable} from './idle-data.js?v=0.69.0';
import {requireRule,journal} from './utils.js?v=0.69.0';
const make=s=>s.idleDispatch??={version:1,revision:0,earned:0,mission:null,bank:{}};
export function accrueIdle(s){const x=s.idleDispatch,m=x?.mission;if(!m)return;ensureGathering(s);const elapsed=Math.max(0,s.clock-m.lastAt),time=m.carry+Math.min(IDLE_CAP,elapsed),cycles=Math.floor(time/IDLE_CYCLE);m.lastAt=s.clock;m.carry=time%IDLE_CYCLE;accrueContacts(s,m,cycles);for(const [id,rate]of Object.entries(idleRates(m.region,m.hero,s))){const old=x.bank[id]||0,n=Math.min(rate*16,old+cycles*rate);if(n>old){x.bank[id]=n;x.earned+=n-old;}}}
export function idleQuote(s,region,hero){return {items:Object.hasOwn(IDLE_ROUTES,region)?idleRates(region,hero,s):{},reason:!s.camp?'先建立寨子。':!Object.hasOwn(IDLE_ROUTES,region)?'请选择派遣地区。':!idleUnlocked(s,region)?'先亲自通关这个地区，任一难度均可。':s.idleDispatch?.mission?'已有好汉在采集，请先接回。':Object.values(s.idleDispatch?.bank||{}).some(n=>n>0)?'先收好上趟暂存材料，再安排新派遣。':!idleAvailable(s,hero)?'请选择未出阵、未任职且不在外派中的好汉。':''};}
export function idleAction(s,d,a){requireRule(s.camp,'先建立寨子。');if(a.type==='idleSend'){const q=idleQuote(s,a.region,a.hero);requireRule(!q.reason,q.reason);ensureGathering(s);const x=make(s);x.mission={region:a.region,hero:a.hero,lastAt:s.clock,carry:0};x.revision++;journal(s,'【采集派遣】'+d.by.heroes[a.hero].name+'前往'+IDLE_ROUTES[a.region].name+'。每半小时带回一批材料，最多暂存八小时；不带兵，不消耗体力和粮草。');return;}
 const x=s.idleDispatch;requireRule(x,'尚未安排采集派遣。');requireRule(['idleCollect','idleRecall'].includes(a.type),'未知派遣操作。');const recall=a.type==='idleRecall';requireRule(!recall||x.mission,'没有待接回的好汉。');let total=0;const got=[];for(const [id,bank]of Object.entries(x.bank)){const n=Math.min(bank,Math.max(0,10000000-(s.inventory[id]||0)));if(n){s.inventory[id]=(s.inventory[id]||0)+n;x.bank[id]-=n;total+=n;got.push(d.by.items[id].name+' +'+n);const h=Object.values(REGION_CONTACTS).find(h=>id===h+'_token');if(h)knowHero(s,h,'heard',d);}if(!x.bank[id])delete x.bank[id];}requireRule(recall||total>0,Object.keys(x.bank).length?'对应材料库存已满，采集所得仍保留。':'尚未采到完整一批材料。');if(recall)x.mission=null;x.revision++;journal(s,'【采集'+(recall?'归寨':'入库')+'】'+(got.length?got.join('、')+'。':'')+(recall?'好汉已回寨，未满一批的时间不计；':'好汉继续在当地采集；')+(Object.keys(x.bank).length?'库存放不下的材料保留，腾出位置后可领取。':'所得已收好。'));}
