import {planSummary,routeDropTable,campaignProgress} from './journey-campaign-ui.js?v=0.44.0';
import {journeyNextGoal,routePrizeLine} from './journey-goals-ui.js?v=0.44.0';
import {journeyBuildPanel,journeyEventNote,journeyBossPreview} from './journey-tactics-ui.js?v=0.44.0';
import {journeyTradeCost,ROUTE_BOSSES,JOURNEYS,JOURNEY_TIERS,JOURNEY_GOALS,BOONS,JOURNEY_NODES,boonPool,journeyGoalReward} from './journey-data.js?v=0.44.0';
import {journeyQuote,journeyFood} from './journey.js?v=0.44.0';import {rotationCalendar} from './rotations.js?v=0.44.0';
function rewardText(goal,tier,d){const r=journeyGoalReward(goal,tier);return [r.wood?'木材 '+r.wood:'',r.food?'粮草 '+r.food:'',...Object.entries(r.items||{}).map(([id,n])=>(d.by.items[id]?.name||id)+' '+n)].filter(Boolean).join('、');}
export function journeyHome(s,btn,d){const t=s.realm?.trek,j=t?.journey,last=s.realm?.journey?.last,g=journeyNextGoal(s,d);return '<section class="journey-home" aria-label="下一步游玩目标"><h2>'+(j?'接着走完这一趟':g.title)+'</h2><p>'+(j?JOURNEYS[j.region].name+' · 已走 '+t.node+'/5 段，战法与暂存物资已保存。':g.text)+'</p>'+btn(j?'继续游历':g.label||'前往准备',j?{type:'ui_section',view:'realm',id:'journey'}:g.command,'primary')+(g.secondary&&!j?btn(g.secondary.label,g.secondary.command,'secondary'):'')+(last&&!j?'<p class="note">'+(last.complete?'上趟已走通':'上趟收队于')+JOURNEYS[last.region].name+'；'+(last.complete?'所得与路契已入库。':'可调整阵容后再试。')+'</p>':'')+'</section>';}
export function journeyPanel(s,d,esc,btn){const t=s.realm?.trek,j=t?.journey,record=s.realm?.journey;
 if(!j){const last=record?.last,tickets=record?.weekly.period===rotationCalendar(s.clock).period?record.weekly.tickets:0;return '<section class="realm-panel journey-panel" data-page-section="realm:journey"><h1>江湖游历</h1>'+planSummary(s,btn)+'<p>选定物资目标，走五段路线；每个路口前选一项临时战法，气血与兵损连续结算。没有每日出发次数限制。</p><label>这趟带回什么<select id="journey-goal">'+Object.entries(JOURNEY_GOALS).map(([id,m])=>'<option value="'+id+'" '+(last?.goal===id?'selected':'')+'>'+m.name+'</option>').join('')+'</select></label><p class="note">走通回寨另得本路路契 2 / 3 / 4，6 契兑换专属装备。走通才有定向物资；提前收队或战败带回暂存物资一半。每次首次走通新难度另获材料自选匣 1；本期前三次走通各得招贤令 1（'+tickets+'/3），各路线共用。</p>'+(last?'<p>上趟：'+JOURNEYS[last.region].name+' · '+JOURNEY_TIERS[last.tier].name+' · '+(last.complete?'已走通':'已收队')+'。'+last.boons.map(id=>BOONS[id].name).join(' / ')+'</p>':'')+'<p>战法图鉴：'+boonPool(s).length+'/20。每条路线首次走通，发现三项战法，加入之后的随机三选一。</p>'+Object.entries(JOURNEYS).map(([id,m],i)=>'<details class="realm-card" data-fold="journey-route-'+id+'" '+(id===(record?.rewards?.target||'forest')?'open data-default-open':'')+'><summary>'+m.name+' · '+(record?.best[id]?JOURNEY_TIERS[record.best[id]].name+'已通':'尚未走通')+'</summary><p>'+m.text+'</p><p class="note">首领：'+ROUTE_BOSSES[id].name+'。'+ROUTE_BOSSES[id].warning+'</p>'+routePrizeLine(s,id,btn)+routeDropTable(id,d)+'<p>首次发现：'+m.discoveries.map(k=>BOONS[k].name).join('、')+'</p>'+Object.entries(JOURNEY_TIERS).map(([key,q])=>{const tier=Number(key),quote=journeyQuote(s,id,tier);return '<div class="journey-tier"><b>'+q.name+'</b><span>体力 '+quote.stamina+' · 启程粮草 '+quote.food+'</span>'+btn('出发 · '+q.name,{type:'ui_journeyStart',region:id,tier},'primary',!!quote.reason)+'<p class="note">'+esc(quote.reason||'战斗另扣粮草；定向物资按此难度发放，强敌辎重收益更高。')+'</p></div>';}).join('')+'</details>').join('')+btn('调整出阵好汉',{type:'ui_section',view:'heroes',id:'formation'},'secondary')+'<details data-fold="journey-codex"><summary>查看已发现战法与定向物资</summary>'+boonPool(s).map(id=>'<p><b>'+BOONS[id].name+'</b> · '+BOONS[id].text+'</p>').join('')+Object.entries(JOURNEY_GOALS).map(([id,m])=>'<p>'+m.name+'：探路 '+rewardText(id,1,d)+'；险途 ×2，绝险 ×3。</p>').join('')+'</details></section>';}
 const m=JOURNEYS[j.region],q=journeyFood(s),node=(kind,choice,label,disabled=false)=>btn(label,{type:'journeyNode',kind,...(choice?{choice}:{})},'secondary',disabled);let choices='';
 if(j.offers.length)choices='<section class="journey-offers"><h2>选一个本趟战法 · '+(j.boons.length+1)+'/5</h2>'+j.offers.map(id=>'<article class="realm-card"><h3>'+BOONS[id].name+'</h3><p>'+BOONS[id].text+'</p>'+btn('选择',{type:'journeyChoice',id},'primary').replace('<button ', '<button aria-label="选择'+BOONS[id].name+'" ')+'</article>').join('')+'</section>';
 else if(t.node<5)choices='<section><h2>第 '+(t.node+1)+' 段 · 选一条路</h2>'+t.route[t.node].map(kind=>{if(['fight','elite','boss'].includes(kind))return '<article class="realm-card"><b>'+JOURNEY_NODES[kind]+'</b><p>敌人：'+(kind==='fight'?m.enemies:m.boss).map(id=>esc(d.by.enemies[id]?.name||id)).join('、')+'；'+(kind==='elite'?'强敌，暂存碎银 '+150*j.tier+'、精铁 '+4*j.tier:kind==='boss'?'走通末段，暂存碎银 '+180*j.tier+'、精铁 '+4*j.tier:'暂存碎银 '+80*j.tier+'、精铁 '+2*j.tier)+'（搜寻辎重另加成）。</p>'+(kind==='boss'?journeyBossPreview(j):'')+journeyEventNote(j)+node(kind,null,'交锋 · 粮草 '+q.food,s.camp.food<q.food||s.camp.mode==='army'&&!q.troops)+'</article>';return '<article class="realm-card"><b>'+JOURNEY_NODES[kind]+'</b><p>'+(kind==='camp'?'休整或补足粮草，二选一。退阵者无法治疗。':kind==='trade'?'买下养成材料，或省下碎银离开。':kind==='event'?(j.rules===2?'护送：货摊半价、首领战前获援助。搜索：下一场多一名追兵、胜利战利品 +20%。':'护送行旅，或冒险翻找遗落辎重。'):'选择一份货物带走。')+'</p>'+(kind==='camp'?node(kind,'rest','粮草 −15 · 气血 +30%',s.camp.food<15)+node(kind,'forage','采粮 +20 · 不恢复气血'):kind==='trade'?node(kind,'buy','碎银 −'+journeyTradeCost(j)+' · 布匹 +'+3*j.tier+'、残页 +'+2*j.tier,s.player.silver<journeyTradeCost(j))+node(kind,'pass','保留碎银，离开'):kind==='event'?node(kind,'rescue','粮草 −15 · 布匹、残页各 +'+2*j.tier,s.camp.food<15)+node(kind,'search','气血 −15% 上限 · 碎银 +'+80*j.tier+'、精铁 +'+2*j.tier):node(kind,'arms','精铁 +'+4*j.tier)+node(kind,'practice','残页 +'+5*j.tier))+'</article>';}).join('')+'</section>';
 return '<section class="realm-panel journey-panel" data-page-section="realm:journey"><h1>'+m.name+' · '+JOURNEY_TIERS[j.tier].name+'</h1><p>已走 '+t.node+'/5 段 · 目标：'+JOURNEY_GOALS[j.goal].name+'</p>'+campaignProgress(j)+(t.node===5?'<p>归路已通。回寨领取本路路契 '+(j.tier+1)+'、暂存物资和 '+rewardText(j.goal,j.tier,d)+'。</p>'+btn('整队回寨 · 领取所得',{type:'journeyReturn'},'primary'):choices)+journeyBuildPanel(j)+journeyEventNote(j)+'<p>'+t.team.map(id=>esc(d.by.heroes[id].name)+' '+(t.hp[id]/100).toFixed(0)+'%').join(' · ')+'</p><p>暂存：碎银 '+t.loot.silver+'、精铁 '+t.loot.iron+'、布匹 '+t.loot.cloth+'、残页 '+t.loot.martial_pages+'</p><section class="journey-route"><h2>整条路线</h2>'+t.route.map((options,i)=>'<p'+(i===t.node?' aria-current="step"':'')+'><b>'+(i<t.node?'✓':i===t.node?'→':'·')+' '+(i+1)+'</b> '+(i<t.node?JOURNEY_NODES[j.path[i]]:options.map(k=>JOURNEY_NODES[k]).join(' / '))+'</p>').join('')+'</section><details data-fold="journey-boons"><summary>本趟战法 '+j.boons.length+' 项 · 查看效果</summary>'+j.boons.map(id=>'<p><b>'+BOONS[id].name+'</b> · '+BOONS[id].text+'</p>').join('')+'</details>'+(t.node<5?'<p class="note">走通额外带回：'+rewardText(j.goal,j.tier,d)+'。退出页面会保存行程；收队会结束本趟。</p>'+btn('野营药包 ×'+(s.inventory.camp_pack||0)+' · 恢复 20%',{type:'provisionUse',id:'camp_pack'},'secondary',!s.inventory.camp_pack||(t.packs||0)>=2||!Object.values(t.hp).some(v=>v>0&&v<10000))+btn('结束本趟 · 带回暂存所得一半',{type:'journeyReturn'},'secondary'):'')+'</section>';
}
