import {SCENE_LIBRARY} from './scene-library.js?v=0.66.0';
import {campScene,SCENE_ART} from './scenes.js?v=0.66.0';
export function sceneBanner(s,esc){const m=campScene(s);return '<button type="button" class="scene-banner scene-'+m.time+'" data-command="'+esc(JSON.stringify({type:'ui_scene',place:'gate'}))+'" aria-label="走到白泽寨门"><img src="'+m.art+'" alt="木寨门外的小路通向聚义厅，右侧是水泊" width="2172" height="724" decoding="async"><span><b>白泽寨</b><small>'+s.camp.buildings.hall+' 级 · '+(m.repaired?'寨门已修整':'水泊初立')+'</small></span><em>入寨看看 ›</em></button>';}
export function scenePage(s,d,esc,btn,portrait,request){const m=campScene(s,request),gate=m.place==='gate',name=m.person?d.by.heroes[m.person].name:'守门乡勇';
 const speaker=gate?(m.person?portrait(d.by.heroes[m.person],true):'<span class="scene-npc-symbol" aria-hidden="true">寨</span>'):'<span class="scene-npc-symbol" aria-hidden="true">林</span>';
 const choices=gate?btn('问问山路',{type:'ui_scene',place:'gate',topic:'road'},'secondary')+btn('寨里怎样',{type:'ui_scene',place:'gate',topic:'camp'},'secondary'):btn('查看车辙',{type:'ui_scene',place:'woods',topic:'tracks'},'secondary')+btn('回寨门',{type:'ui_scene',place:'gate'},'secondary');
 const action=gate?btn('去林口看看',{type:'ui_scene',place:'woods'},'primary')+(s.camp.wounded?btn(s.camp.buildings.clinic?'去医馆':'先建医馆',{type:'ui_section',view:'camp',id:s.camp.buildings.clinic?'troops':'buildings'},'secondary'):btn('料理寨务',{type:'ui_section',view:'camp',id:'buildings'},'secondary')):btn('整队清剿',{type:'campRaid',id:'woods'},'primary',!!m.reason);
 return '<section class="scene-visit" data-page-section="camp:scene"><header><h1>'+m.title+'</h1>'+btn('返回总览',{type:'ui_section',view:'camp',id:'home'},'text-action')+'</header><button type="button" class="scene-image scene-'+m.time+'" data-command="'+esc(JSON.stringify({type:'ui_sceneArt',id:m.place==='woods'?'woods':m.repaired?'repaired':'gate'}))+'" aria-label="查看'+m.title+'大图"><img src="'+m.art+'" alt="'+(gate?'木寨门、聚义厅与水泊':'林间小路旁倒着一辆木车，远处可望见水泊')+'" width="2172" height="724"><small>看大图</small></button><p class="scene-caption">'+esc(m.caption)+'</p><div class="scene-conversation">'+speaker+'<div><strong>'+esc(gate?name:'路旁痕迹')+'</strong><p>'+esc(m.text)+'</p></div></div><div class="scene-choices">'+choices+'</div>'+(!gate?'<p class="scene-cost">'+esc(m.reason||'出征：体力 8 · 粮草 '+m.food+' · '+(m.troops?m.troops+' 人随军':'好汉独行'))+'</p>':'')+'<div class="scene-actions">'+action+'</div></section>';
}
export function sceneArtDialog(id,esc,btn){if(!Object.hasOwn(SCENE_LIBRARY,id))return '';const art=SCENE_LIBRARY[id];return '<dialog id="scene-art" class="compact-dialog" aria-labelledby="scene-art-title"><header class="dialog-header"><h2 id="scene-art-title" tabindex="-1">'+esc(art.title)+'</h2></header><div class="dialog-body"><img class="scene-full-art" src="'+esc(art.src)+'" alt="'+esc(art.alt)+'" width="'+art.width+'" height="'+art.height+'"></div><footer class="dialog-footer">'+btn('收起画卷',{type:'ui_sceneArtClose'},'secondary')+'</footer></dialog>';}
export function woodlandPreview(a){return a.type==='campRaid'&&a.id==='woods'?'<img class="scene-sortie-image" src="'+SCENE_ART.woods+'" alt="即将前往的林口山路" width="2172" height="724">':'';}
