import { HERO_SPECIALTIES, STYLES, TERRAIN_NAMES, JOB_NAMES, BONDS, DRILLS, MECHANICS, activeBonds } from './strategy-data.js?v=0.15.0';
import { drillQuote } from './strategy.js?v=0.15.0';
export function specialtyPanel(s,d,h,btn){
 const p=HERO_SPECIALTIES[h.id],choice=s.strategy?.drills[h.id],q=drillQuote(s,h.id),busy=!!(s.battle||s.scheme||s.event);
 return `<section class="hero-specialty"><h3>${h.name} · 行军与任职</h3><p><b>${TERRAIN_NAMES[p.terrain]}专长：</b>对应地形直接伤害 +12%，独行与带兵均生效。</p><p><b>${STYLES[p.style].name}：</b>${STYLES[p.style].text}</p><p class="note">任职${JOB_NAMES[p.job]}时，每半小时额外 +1 ${p.job==='workshop'?'加工额度':'份产出'}；任职英雄出征时暂停加成。以上战斗专长仅建寨后的非剧情新战局生效。</p>
 <details data-fold="drill-${h.id}"><summary>部队专精 · ${choice?DRILLS[choice].name:'常规训练'}</summary><p class="note">专精仅实际分到乡勇时生效，独行不受影响。每次训练或改练消耗碎银 200、武学残页 3、精铁 3；撤销不返材料。</p>${Object.entries(DRILLS).map(([id,v])=>`<p><b>${v.name}：</b>${v.text}</p>${btn(choice===id?'已采用'+v.name:'训练'+v.name,{type:'drillTrain',id:h.id,choice:id},'secondary',busy||!!q.reason||choice===id)}`).join('')}<p class="note">${q.reason||'已满足条件，可选择训练方向。'}</p>${btn('恢复常规训练',{type:'drillTrain',id:h.id,choice:null},'text-action',busy||!choice)}</details></section>`;
}
const statName={attack:'攻击',defense:'防御',hp:'气血',speed:'速度',strategy:'谋略',rage:'开战怒气'};
export function bondsPanel(s,d){
 if(!s.camp)return '';const active=activeBonds(s.team,'land');
 return `<details class="fold-section" data-fold="party-bonds"><summary>阵容羁绊 · 12 组搭配${active.length?' · 平原已激活 '+active.length+' 组':''}</summary><p class="note">所列好汉必须同时出阵，效果作用于全队；独行与带兵均可触发。地形限定在对应战场才生效，不要求坐骑羁绊。</p><div class="bond-grid">${BONDS.map(g=>{const missing=g.heroes.filter(id=>!s.team.includes(id));return `<article class="card"><h3>${g.name}</h3><p>${g.heroes.map(id=>d.by.heroes[id].name).join(' · ')}</p><p class="meta">${g.terrain?TERRAIN_NAMES[g.terrain]+'限定 · ':''}全队${statName[g.stat]} +${g.stat==='rage'?g.rate:Math.round(g.rate*100)+'%'}</p><p class="note">${missing.length?'待编入：'+missing.map(id=>d.by.heroes[id].name).join('、'):g.terrain?'人员齐备，在'+TERRAIN_NAMES[g.terrain]+'生效':'当前阵容可触发'}</p></article>`;}).join('')}</div></details>`;
}
export function mechanicPreview(id){const m=MECHANICS[id];return m?`<div class="mechanic-preview"><b>${m.name} · ${TERRAIN_NAMES[m.terrain]}</b><p class="note">${m.text}</p></div>`:'';}
export function objectivePanel(b){const o=b.depth?.objective,m=MECHANICS[o?.kind];if(!m)return '';return `<section class="objective-panel" aria-label="副本目标"><h2 class="subhead">${m.name}</h2>${['stable','convoy'].includes(o.kind)?`<p>护运耐久 <strong>${o.integrity} / 100</strong></p><progress value="${o.integrity}" max="100" aria-label="护运耐久"></progress>`:m.deadline?`<p>剩余时限 <strong>${Math.max(0,Math.ceil((m.deadline-b.elapsed)/1000))} 秒</strong></p>`:o.kind==='fortress'?`<p>敌军补给 ${o.waves} / 3 次</p>`:''}${o.nextAt&&!b.outcome?`<p class="meta">下一次${o.kind==='tide'?'潮汐':o.kind==='fortress'?'补给':'袭扰'}：${Math.ceil((o.nextAt-b.elapsed)/1000)} 秒</p>`:''}<details data-fold="objective-help"><summary>应对提示</summary><p class="note">${m.text}</p></details></section>`;}
