import { attributes } from './hero.js';
import { exits, meets, heroRank } from './map.js';
import { isBusy, questReady } from './core.js';
import { statusName } from './battle.js';
export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
const btn=(label,command,kind='text-action',disabled=false)=>`<button type="button" class="${kind}" data-command="${esc(JSON.stringify(command))}" ${disabled?'disabled':''}>${esc(label)}</button>`;
const nav=(label,view)=>`<button class="text-action" data-view="${view}">${esc(label)}</button>`;
const stats=a=>`<div class="statline">${Object.entries({气血:a.hp,攻击:a.attack,防御:a.defense,速度:a.speed,谋略:a.strategy}).map(([k,v])=>`<span>${k} ${v}</span>`).join('')}</div>`;
const title=(name,sub='')=>`<div class="section-top"><div><p class="kicker">${esc(sub)}</p><h1>${esc(name)}</h1></div><span class="chapter-no">卷一</span></div>`;
const statusLabels={unknown:'未闻',heard:'听闻',known:'相识',available:'可招贤',owned:'已入寨'};
function heroOptions(s,d,selected='',empty='选择好汉'){return `<option value="">${empty}</option>`+d.heroes.filter(h=>s.heroes[h.id].status==='owned').map(h=>`<option value="${h.id}" ${selected===h.id?'selected':''}>${h.name} · ${s.heroes[h.id].level}级</option>`).join('');}
function storyCards(s,d) {
  return d.by.maps[s.location].stories.map(id=>{
    const model=d.by.stories[id],p=s.progress.stories[id];
    if(p?.status==='completed')return `<p class="note">${esc(model.title)}已记入梁山志。</p>`;
    if(!p)return model.map===s.location&&meets(s,model.condition)?`<article class="card"><h2>${esc(model.title)}</h2>${btn('开始这段相识',{type:'story',id})}</article>`:'';
    const step=model.steps[p.step];if(step.map!==s.location||!meets(s,step.condition))return '';
    return `<article class="card"><p class="kicker">${esc(model.title)} · 往事进行中</p><p class="prose">${esc(step.text)}</p><div class="actions">${step.choices.map(c=>btn(c.label,{type:'story',id,choice:c.id},'primary')).join('')}</div></article>`;
  }).join('');
}
function mapPage(s,d){const m=d.by.maps[s.location];return title(m.name,m.region+' · '+(s.worldMinute>=1080||s.worldMinute<360?'夜色渐深':'白日行路'))+
  `<section class="location"><p class="prose">${esc(m.description)}</p><p class="subhead">可往何处</p><div class="paths">${exits(s,d).map(l=>btn(d.by.maps[l.target].name,{type:'move',id:l.target})).join('')}</div></section>`+
  storyCards(s,d)+m.actions.filter(a=>!a.once||!s.progress.actions[a.id]).map(a=>btn(a.label,{type:'mapAction',id:a.id})).join(' ')+
  d.heroes.filter(h=>h.meetMap===s.location&&meets(s,h.meetCondition)&&heroRank[s.heroes[h.id].status]<2).map(h=>btn(h.id==='baisheng'?'与卖酒汉子交谈':h.id==='shiqian'?'与窗边瘦汉交谈':'与'+h.title+'交谈',{type:'meet',id:h.id})).join(' ')+
  (s.location==='tavern'&&s.heroes.baisheng.status==='known'&&!s.progress.flags.guide?`<article class="card"><h2>乡人相助</h2><p>白胜拍了拍酒担：“乡道我熟，可先替你照应行路。”</p>${btn('邀白胜作向导',{type:'guide'},'primary')}</article>`:'')+
  (s.location==='ridge'&&s.progress.flags.seven_stars&&!s.progress.flags.huangni_complete?`<article class="card"><h2>智取生辰纲</h2><p>你负责察看时机，吴用、晁盖等人依计行事。这里不靠强攻。</p>${btn('商议冈上的安排',{type:'startScheme'},'primary')}</article>`:'')+
  (s.location==='forge'?forgePage(s,d,false):s.location==='recruit'?recruitPage(s,d,false):s.location==='office'?nav('查看主线与今日差事','quests'):'')+
  m.dungeons.map(id=>{const x=d.by.dungeons[id],open=meets(s,x.condition);return `<article class="card"><h2>${esc(x.name)}<span class="badge">历练</span></h2><p class="note">${esc(x.description)}</p><p class="meta">队中一人达到 ${x.level}级 · 体力 ${x.cost} · 今日 ${s.daily.dungeons[id]||0}/${x.limit} 次</p>${btn(open?'开始历练':'需先完成此地剧情',{type:'dungeon',id},'secondary',!open||s.team.length===0||Math.max(...s.team.map(id=>s.heroes[id].level))<x.level||(s.daily.dungeons[id]||0)>=x.limit||s.player.stamina<x.cost)}</article>`;}).join('')+
  `<article class="card"><h2>江湖寻访</h2><p class="note">寻访耗体力 2；每处际遇每日一次。今日已访 ${s.daily.counters.search||0}/12 回。等候可改变游戏昼夜，不加速真实体力恢复。</p><div class="actions">${btn('四下寻访',{type:'search'},'secondary',s.player.stamina<2||(s.daily.counters.search||0)>=12)}${btn('等候半日',{type:'wait'})}</div></article>`;
}
function heroesPage(s,d){return title('我的好汉','识人 · 招贤 · 排兵布阵')+`<section class="location"><h2 class="subhead">出阵次序 · 最多三人</h2><p class="note">前两位迎敌，第三位居后照应。阵中没有寨主，你只负责指挥。</p>${[0,1,2].map(i=>`<label>第 ${i+1} 位<select id="team-${i}" aria-label="第${i+1}位出阵好汉">${heroOptions(s,d,s.team[i])}</select></label>`).join('')}${btn('保存阵容',{type:'ui_team'},'primary')}</section>`+
  d.heroes.map(h=>{const v=s.heroes[h.id];if(v.status==='unknown')return `<article class="card"><h2>尚未听闻的好汉</h2><span class="meta">江湖自有相逢处 · 未闻</span></article>`;
    return `<article class="card"><h2>${esc(h.title)} · ${esc(h.name)}<span class="badge">${statusLabels[v.status]}</span></h2><p class="note">${esc(h.story)}</p><p class="meta">${'★'.repeat(h.star)} · ${v.status==='owned'?v.level+'级 · 经验 '+v.exp+' / '+(20+v.level*15):'先相识，再以信物邀贤'}</p>${v.status==='owned'?stats(attributes(s,h.id,d))+btn('赠经验丹（现有 '+(s.inventory.exp_pill||0)+'）',{type:'use',id:'exp_pill',hero:h.id},'secondary',!s.inventory.exp_pill||v.level>=40):`<p class="note">可在${esc(d.by.maps[h.meetMap].name)}寻访${h.meetCondition?'，还须推进相关主线':''}。</p>`}<p class="meta">信物 ${s.inventory[h.id+'_token']||0}/10 · 专属令 ${s.inventory[h.id+'_order']||0}</p><details><summary>查看招式</summary>${h.skills.map(id=>`<p>【${esc(d.by.skills[id].name)}】${esc(d.by.skills[id].description)}${d.by.skills[id].cost?' · 怒气 '+d.by.skills[id].cost:''}</p>`).join('')}</details></article>`;}).join('');}
function equipmentList(s,d,forge=false){return s.equipment.map(e=>{const m=d.by.equipments[e.item];return `<article class="card"><h3>${esc(m.quality)} · ${esc(m.name)} +${e.plus}</h3><p class="meta">${e.hero?'由'+d.by.heroes[e.hero].name+'穿戴':'行囊中'} · ${Object.entries(m.attribute).map(([key,n])=>({attack:'攻击',hp:'气血',defense:'防御',speed:'速度',strategy:'谋略'})[key]+' +'+Math.round(n*(1+e.plus*.1))).join(' / ')}</p><label>交给<select id="holder-${e.uid}" aria-label="${m.name}穿戴者">${heroOptions(s,d,e.hero,'卸下收回')}</select></label>${btn('确认穿戴',{type:'ui_equip',id:e.uid},'secondary')}${forge?`<div class="actions">${btn('强化：碎银 '+50*(e.plus+1)+'、精铁 '+(e.plus+1),{type:'strengthen',id:e.uid},'secondary',e.plus>=5)}${btn('分解成碎铁',{type:'ui_dismantle',id:e.uid},'text-action',!!e.hero)}</div>`:''}</article>`;}).join('');}
function bagPage(s,d){return title('行囊','行路之物 · 一件也有来处')+`<div class="grid-two">${d.items.filter(i=>(s.inventory[i.id]||0)>0).map(i=>`<article class="card"><h3>${esc(i.name)} ×${s.inventory[i.id]}</h3><p class="note">${esc(i.description)}</p>${i.effect.stamina?btn('小饮一碗',{type:'use',id:i.id},'secondary'):i.effect.exp?nav('选择好汉赠经验丹','heroes'):''}</article>`).join('')}</div><h2 class="subhead">材料合成</h2><div class="actions">${btn('10 招贤碎片 → 招贤令',{type:'exchange',id:'order'},'secondary')}${btn('3 药草 → 2 金创药',{type:'exchange',id:'medicine'},'secondary')}${btn('20 生辰纲残册 → 失落财货',{type:'exchange',id:'ledger'},'secondary')}${btn('5 强化符碎片 → 强化符',{type:'exchange',id:'charm'},'secondary')}</div><h2 class="subhead">随身装备</h2>${equipmentList(s,d)}<h2 class="subhead">城中采买</h2><p class="note">到郓城集市、铁匠铺、酒肆、招贤馆或药草坡才可交易。招贤令每日限购三张。</p><div class="actions">${['jinchuangyao','huiqisan','jiedudan','exp_pill','wine','iron','cloth','night_clothes','recruit_order'].map(id=>btn(`${d.by.items[id].name} · ${d.by.items[id].price}银`,{type:'buy',id},'secondary',!['yuncheng','forge','herbs','tavern','recruit'].includes(s.location))).join('')}</div>`;}
function forgePage(s,d,heading=true){return (heading?title('铁匠铺','基础打造 · 强化至 +5'):'')+`<p class="note">基础强化必成；穿戴中的装备不能分解。制造消耗碎银和材料，购买只消耗双倍碎银。</p>${equipmentList(s,d,true)}<details><summary>打造与购买二十种基础装备</summary>${d.equipments.map(e=>`<article class="card"><h3>${esc(e.quality)} · ${esc(e.name)}</h3><p class="meta">打造：${e.recipe.silver}银，${Object.entries(e.recipe.items).map(([id,n])=>d.by.items[id].name+' ×'+n).join('，')}</p><div class="actions">${btn('打造',{type:'craftEquip',id:e.id},'secondary')}${btn('购买 · '+e.price*2+'银',{type:'buyEquip',id:e.id})}</div></article>`).join('')}</details>`;}
function recruitPage(s,d,heading=true){const at=s.location==='recruit';return (heading?title('招贤馆','一面之缘 · 还须诚心相邀'):'')+(!at?'<p class="warning">你尚未身在招贤馆。请从地图回到郓城，再进入招贤馆。</p>':'')+
  `<section class="location"><h2 class="subhead">普通招贤</h2><p class="prose">墙上的英雄帖已有些旧了。相识之人可应邀入寨，尚未相识的核心人物只托人送回线索与信物。</p><p>招贤令 ×${s.inventory.recruit_order||0}</p>${btn('使用一张招贤令',{type:'recruit'},'primary',!at||!s.inventory.recruit_order)}<details><summary>查看招贤规则与保底</summary><p>五星 1%、四星 6%、三星 23%、二星 45%、一星 25%。连续未得三星 ${s.recruit.pity.three}/20、四星 ${s.recruit.pity.four}/50、五星 ${s.recruit.pity.five}/100；达到次数必得相应档次或以上的结果。未相识者仍只送来两枚信物，不跳过人物剧情。</p><p>专属招贤：目标 25%、其他五星 5%、其余 70%。连续四次未得目标后，下一次必得。重复好汉化为三枚对应信物与功勋十五。无付费招贤。</p></details></section>`+
  d.heroes.filter(h=>heroRank[s.heroes[h.id].status]>=1).map(h=>`<article class="card"><h2>${h.title} · ${h.name}</h2><p class="meta">${statusLabels[s.heroes[h.id].status]} · 信物 ${s.inventory[h.id+'_token']||0}/10 · 专属令 ${s.inventory[h.id+'_order']||0} · 缘分 ${s.recruit.fate[h.id]||0}/4</p><div class="actions">${btn('合成专属令',{type:'craftOrder',id:h.id},'secondary',(s.inventory[h.id+'_token']||0)<10)}${btn('专属招贤',{type:'recruit',id:h.id},'primary',!at||heroRank[s.heroes[h.id].status]<2||!s.inventory[h.id+'_order'])}</div></article>`).join('');}
function rewardText(r,d){return [...['silver','merit','prestige'].filter(k=>r[k]).map(k=>({silver:'碎银',merit:'功勋',prestige:'威望'})[k]+' ×'+r[k]),...Object.entries(r.items||{}).map(([id,n])=>d.by.items[id].name+' ×'+n)].join('，');}
function questsPage(s,d){return title('今日江湖','榜文与差事 · '+s.daily.date)+['main','daily'].map(kind=>`<h2 class="subhead">${kind==='main'?'第一卷主线':'今日差事 · 从十二种中按进度派发三份'}</h2>${d.quests.filter(q=>q.type===kind&&(kind==='main'||s.daily.ids.includes(q.id))).map(q=>{const claimed=(kind==='main'?s.progress.claims:s.daily.claimed).includes(q.id),ready=questReady(s,q);return `<article class="card"><h3>${q.name}${claimed?'<span class="badge">已办妥</span>':''}</h3><p>${esc(q.description)}</p><p class="meta">${kind==='daily'?'进度 '+Math.min(q.goal.amount,s.daily.counters[q.goal.stat]||0)+'/'+q.goal.amount+' · ':''}酬劳：${rewardText(q.reward,d)}</p>${btn(claimed?'酬劳已领':ready?'领取酬劳':'尚待办妥',{type:'quest',id:q.id},'secondary',claimed||!ready)}</article>`;}).join('')}`).join('')+`<div class="actions">${btn(s.daily.bonus?'今日额外酬劳已领':'领齐三份差事后的额外酬劳',{type:'dailyBonus'},'primary',s.daily.bonus||s.daily.claimed.length!==3)}</div><p class="note">每日按本机日期更新，不重置主线。修改系统时间不是可靠的游玩方式；本地存档不提供服务器防作弊。</p>`;}
function chroniclePage(s,d){return title('白泽梁山志','你的相逢、胜败与归处')+(s.progress.flags.volume_complete?`<section class="complete"><h2>郓城风起 · 卷终</h2><p>初级据点已立。渡口传来东京与沧州的风声，林冲、鲁智深与更多江湖人的往事还在远方。</p><p class="note">可继续本卷历练、养成与收集。第二卷完整剧情、建筑升级和坐骑养成尚未开放。</p></section>`:'')+`<p>建寨记事始于 ${esc(new Date(s.startedAt).toLocaleString('zh-CN'))}。晁盖、阮小二和阮小五为本卷剧情人物，不计入十二名正式好汉。</p><ul class="plain-list">${[...s.journal].reverse().map(e=>`<li><time>${esc(new Date(e.at).toLocaleString('zh-CN'))}</time>${esc(e.text)}</li>`).join('')}</ul><p class="note">保留最近三百条详细记事；人物、主线与通关累计不会随旧日志截断。</p>`;}
function savePage(s,status,locked){return title('存档与归卷','独立本机存档 · 不与学习记录混用')+`<p class="notice ${locked?'error':''}">${esc(status)}</p><p>存档保存在当前浏览器的本机空间。换设备或浏览器时，先导出，再在另一端导入。无痕窗口关闭后通常不会保留进度。</p><div class="actions">${btn('导出当前进度',{type:'ui_export'},'primary')}${btn('重新载入本机存档',{type:'ui_reload'},'secondary')}${btn('恢复上次有效备份',{type:'ui_backup'},'secondary')}</div><label>选择存档 JSON 文件<input id="import-file" type="file" accept=".json,application/json"></label><label for="import-text">或粘贴存档文本</label><textarea id="import-text" spellcheck="false" placeholder="在这里粘贴导出的 JSON"></textarea><div class="actions">${btn('检查导入内容',{type:'ui_import'},'secondary')}</div><p class="note">先校验并预览，确认后才替换本机进度。坏档、未知版本和错误引用不会被直接写入。多标签页同时游玩时，发现冲突会停止写入，避免覆盖另一页。</p><div class="danger-zone"><h2 class="subhead">另开新卷</h2><p class="note">会替换当前游戏进度。建议先导出；不影响导航、博客、Inbox 或学习记录。</p><label>输入“白泽新卷”确认<input id="reset-phrase" autocomplete="off"></label>${btn('确认另开新卷',{type:'ui_reset'},'danger')}</div>`;}
function battlePage(s,d){const b=s.battle;return title(b.guest?'景阳冈 · 剧情战':'阵前指挥','第 '+b.round+' 回合 · '+(b.guest?'武松临时助阵，战后不自动入寨':'按速度先后行动'))+`<div class="grid-two">${[['我方',b.team],['敌方',b.enemy]].map(([label,units])=>`<section><h2 class="subhead">${label}</h2>${units.map(u=>`<div class="battle-unit"><div class="ledger-line"><strong>${esc(u.name)}</strong><span>${u.hp}/${u.maxHp}</span></div><progress value="${u.hp}" max="${u.maxHp}" aria-label="${esc(u.name)}气血"></progress><p class="meta">怒气 ${u.rage}/100 · 速度 ${u.speed} ${u.statuses.map(s=>'【'+statusName(s.id)+'·'+s.turns+'】').join('')}</p></div>`).join('')}</section>`).join('')}</div><p class="battle-teaser">${b.outcome?'战局已定，请收拢队伍。':esc(d.by.enemies[b.enemy.find(e=>e.hp>0)?.model||b.enemy[0].model].telegraphs[(b.round-1)%d.by.enemies[b.enemy.find(e=>e.hp>0)?.model||b.enemy[0].model].telegraphs.length])}</p><div class="combat-log" role="log" aria-label="战斗日志">${b.log.map(t=>`<p>${esc(t)}</p>`).join('')}</div>${b.outcome?`<div class="actions">${btn(b.outcome==='victory'?'收获战果，继续前行':'收兵，再作安排',{type:'finishBattle'},'primary')}</div>`:`<div class="command-row">${btn('强攻',{type:'turn',id:'attack'},'primary')}${btn('防守',{type:'turn',id:'guard'},'secondary')}${btn('计谋 · 观察',{type:'turn',id:'scheme'},'secondary')}${btn('撤退',{type:'turn',id:'retreat'},'text-action')}</div><p class="note">强攻时怒气足够会自动施展武技；计谋优先施展军师或照应招式，否则蓄势观察。防守减少一半伤害并积攒怒气。用药消耗一回合，同伴收势掩护。</p><div class="actions">${['jinchuangyao','huiqisan','jiedudan'].map(id=>btn(`${d.by.items[id].name} ×${s.inventory[id]||0}`,{type:'turn',id:'item',item:id},'secondary',!s.inventory[id])).join('')}</div>`}`;}
function schemePage(s,d){const q=s.scheme,m=d.by.schemes[q.id];return title(m.name,'察看暑热与人心 · 第 '+q.turn+' / '+m.maxTurns+' 次安排')+`<section class="location"><p class="prose">${q.values.alert>=50?'杨志握紧了刀柄，目光一直追着酒担。':q.values.fatigue>=60?'军汉汗流浃背，几乎抬不起担子。':q.values.trust>=50?'军汉看着枣客饮酒，神色渐缓。':'军汉虽想歇脚，杨志却仍紧盯四周。'}</p><p class="note">你看不到人心的刻度，只能从言行作判断。先等暑热与疲劳，再以自然的举动消去疑心。</p></section><div class="combat-log" role="log" aria-label="计策记录">${q.log.map(t=>`<p>${esc(t)}</p>`).join('')}</div><div class="actions">${q.outcome?btn(q.outcome==='success'?'收下信物，记入梁山志':'退出重整计策',{type:'finishScheme'},'primary'):m.choices.map(c=>btn(c.label,{type:'scheme',id:c.id},'secondary')).join('')+btn('判断时机已到，收网',{type:'scheme',id:'finish'},'primary')+btn('暂退',{type:'scheme',id:'retreat'})}</div>`;}
function eventPage(s,d){const e=d.by.events[s.event.id];return title(e.name,'路上际遇')+`<section class="location"><p class="prose">${esc(e.text)}</p><div class="actions">${e.options.map(c=>btn(c.label,{type:'eventChoice',id:c.id},'secondary')).join('')}</div></section>`;}
function sidebar(s,d){const owned=Object.values(s.heroes).filter(h=>h.status==='owned').length;const next=d.quests.find(q=>q.type==='main'&&!s.progress.claims.includes(q.id));return `<aside class="sidebar"><section><h2>此刻的梁山</h2>${[['寨主',s.player.title],['正式好汉',owned+' / 12'],['探访地点',s.progress.visited.length+' / 30'],['历练得胜',(s.stats.clears||0)+' 回'],['当前据点',s.player.liangshanLevel?'梁山初立':'尚未落脚']].map(([a,b])=>`<div class="ledger-line"><span>${a}</span><b>${b}</b></div>`).join('')}</section><section><h2>眼下线索</h2><p>${esc(next?.description||'继续历练，结识同行的人。')}</p>${!owned?'<p>先到郓城酒肆与卖酒汉子交谈，可邀白胜引路。景阳冈剧情由武松临时助阵。</p>':''}<p>人物相识不等于入寨；信物与专属招贤将继续这段缘分。</p></section><section><h2>卷终所需</h2><ol>${[[s.progress.flags.tiger_complete,'景阳冈虎患已平'],[s.progress.flags.huangni_complete,'智取生辰纲'],[owned>=3,'至少三名正式好汉'],[(s.stats.clears||0)>=10,'完成十次历练'],[s.player.prestige>=150,'威望达到一百五十']].map(([ok,text])=>`<li class="${ok?'progress-label':''}">${ok?'已成 · ':'尚待 · '}${text}</li>`).join('')}</ol></section></aside>`;}
export function render({state:s,data:d,view,status,error,locked}){
  const busy=isBusy(s),tabs=[['map','江湖'],['heroes','好汉'],['bag','行囊'],['recruit','招贤'],['quests','差事'],['chronicle','梁山志'],['save','存档']];
  let content=view==='save'?savePage(s,status,locked):view==='chronicle'?chroniclePage(s,d):s.battle?battlePage(s,d):s.scheme?schemePage(s,d):s.event?eventPage(s,d):view==='heroes'?heroesPage(s,d):view==='bag'?bagPage(s,d):view==='recruit'?recruitPage(s,d):view==='quests'?questsPage(s,d):mapPage(s,d);
  if(view==='welcome')content=`<section class="intro"><p class="kicker">第一卷 · 郓城风起</p><h1>江湖，由此入卷。</h1><div class="intro-line"></div>${d.config.opening.map(t=>`<p class="prose">${esc(t)}</p>`).join('')}${btn('进入郓城县',{type:'ui_start'},'primary')}<p class="note">纯文字策略游戏 · 自动本地存档 · 无付费、无账户</p></section>`;
  return `<div class="shell"><header class="masthead"><div class="brand"><span class="seal" aria-hidden="true">白泽</span><div><strong>白泽水浒</strong><p class="kicker">一页文字，一片江湖。</p></div></div><div class="mast-links"><span class="edition">Vol. 01 / 0.1.0</span><a href="../">返回白泽导航</a></div></header><div class="resources"><span>寨主<b>白泽</b></span><span>碎银<b>${s.player.silver}</b></span><span>威望<b>${s.player.prestige}</b></span><span>功勋<b>${s.player.merit}</b></span><span>体力<b>${s.player.stamina}/100</b></span><span>出阵<b>${s.team.length}/3</b></span></div><div class="layout"><aside class="rail"><h2>江湖行箧</h2><nav class="tabs" aria-label="游戏页面">${tabs.map(([id,label],i)=>`<button type="button" data-view="${id}" aria-current="${view===id?'page':'false'}" ${busy&&!['map','save','chronicle'].includes(id)?'disabled':''}><span class="tab-no">0${i+1}</span>${label}</button>`).join('')}</nav><p class="rail-note">不替英雄出拳，<br>只为好汉掌灯。<br><br>本机独立存档<br>建议定期导出</p></aside><main class="main" id="main" tabindex="-1">${view==='welcome'?'':`<div class="notice ${error?'error':''}" role="status">${esc(error||s.message)}</div>`}${locked||!status.startsWith('已保存')?`<p class="warning">${esc(status)}</p>`:''}${content}</main>${sidebar(s,d)}</div><footer class="footer"><span>郓城风起 · ${esc(status)}</span><span>纯文字 / 本机保存 / 无后台服务</span></footer></div>`;
}
export function importDialog(state){return `<dialog id="import-confirm" aria-labelledby="import-title"><h2 id="import-title">确认接续这份梁山志？</h2><p>此存档记录到 ${esc(new Date(state.clock).toLocaleString('zh-CN'))}。</p><p>威望 ${state.player.prestige}，正式好汉 ${Object.values(state.heroes).filter(h=>h.status==='owned').length} 名。</p><p class="note">确认后替换当前游戏进度，并备份原来的有效存档。不影响学习系统。建议先导出当前进度。</p><div class="actions">${btn('确认导入并替换',{type:'ui_confirmImport'},'primary')}${btn('取消',{type:'ui_cancelImport'},'secondary')}</div></dialog>`;}
