import {PERSONAL,COMBOS,LAYOUTS} from './expansion-data.js?v=0.32.0';
import {expansion} from './expansion-state.js?v=0.32.0';
import {startBattle} from './battle.js?v=0.32.0';import {attachTroops} from './camp.js?v=0.32.0';
import {deployedTroops,heroCommand} from './logistics.js?v=0.32.0';
import {affairReward} from './affairs.js?v=0.32.0';import {grant} from './item.js?v=0.32.0';import {requireRule,hasOwn,count,journal} from './utils.js?v=0.32.0';
function enter(s,d,kind,id,enemies,scale,terrain,n){requireRule(s.camp.mode==='solo'||n>0,'请募兵或改为独行。');startBattle(s,d,{enemies,scale,context:{type:'realm',kind,id,terrain,tier:(s.expansion.run?.stage||0)+1}});attachTroops(s,n);}
export function personalReason(s,id){if(!hasOwn(PERSONAL,id)||s.heroes[id]?.status!=='owned'||s.heroes[id].level<10)return '本人入寨并达到 10 级';if(!s.team.includes(id))return '请将本人编入阵容';const n=deployedTroops(s);if(id==='linchong'&&n<50)return '需要随军至少 50 人';if(id==='ruanxiaoqi'&&n<100)return '需要随军至少 100 人';if(id==='huarong'&&(s.team.length!==1||s.camp.mode!=='solo'))return '花荣单人独行';return '';}
export function ventureAction(s,d,a){const x=expansion(s);requireRule(s.realm&&s.camp,'先开启山河经营。');if(a.type==='personalStart'){requireRule(s.camp.buildings.hall>=2,'聚义厅需要 2 级。');requireRule(!x.personal[a.id],'此专属任务已经完成。');requireRule(!personalReason(s,a.id),personalReason(s,a.id));requireRule((s.daily.counters.personal_attempt||0)<3,'专属任务每天合计三次。');const n=deployedTroops(s),food=5+Math.ceil(n/2);requireRule(s.player.stamina>=10&&s.camp.food>=food,'体力 10 或粮草不足。');s.player.stamina-=10;s.camp.food-=food;count(s,'personal_attempt');const m=PERSONAL[a.id];enter(s,d,'personal',a.id,m.enemies,m.scale,m.terrain,n);return;}
 if(a.type==='ventureStart'){requireRule(['defense','relay'].includes(a.kind)&&s.camp.buildings.hall>=3&&!x.run&&!s.realm.trek,'聚义厅 3 级且没有正在进行的远征。');requireRule(!s.daily.counters['venture_'+a.kind],'今日已经开始过此战役。');requireRule(s.team.length&&s.player.stamina>=15&&s.camp.food>=20,'需要已安排主队、体力 15、粮草 20。');if(a.kind==='defense'){requireRule(hasOwn(LAYOUTS,a.layout)&&s.camp.wood>=40&&s.player.silver>=80,'防守需选择布防，并支付木材 40、碎银 80。');s.camp.wood-=40;s.player.silver-=80;}else requireRule(Object.values(s.heroes).filter(h=>h.status==='owned').length>=3,'接力至少需要三位已入寨好汉。');s.player.stamina-=15;s.camp.food-=20;count(s,'venture_'+a.kind);x.run={kind:a.kind,stage:0,used:[],team:[...s.team],hp:Object.fromEntries(s.team.map(id=>[id,10000])),layout:a.kind==='defense'?a.layout:null,loot:{silver:0,iron:0}};journal(s,'【战役启程】'+(a.kind==='defense'?'三波寨防':'三队接力')+'开始，主动推进，不补算离线战斗。');return;}
 if(a.type==='ventureReturn'){requireRule(x.run,'没有进行中的战役。');finishRun(s,d,x.run.stage===3);return;}
 const r=x.run;requireRule(a.type==='ventureNext'&&r&&r.stage<3&&s.team.length,'没有可推进的战役。');if(r.kind==='defense')requireRule(JSON.stringify(s.team)===JSON.stringify(r.team),'寨防途中不能更换英雄。');else requireRule(s.team.every(id=>!r.used.includes(id)),'接力不能重复使用已经出阵的好汉，请更换队伍。');const ids=r.kind==='defense'?s.team.filter(id=>r.hp[id]>0):s.team;requireRule(ids.length,'全队已退阵，请收队。');const n=Math.min(deployedTroops(s),ids.reduce((n,id)=>n+heroCommand(s,id),0)),food=5+Math.ceil(n/5);requireRule(s.camp.food>=food,'本场需粮草 '+food+'。');s.camp.food-=food;if(r.kind==='relay')r.used.push(...s.team);enter(s,d,r.kind,'venture',['bandit','soldier','bandit_chief'].slice(r.stage===2?1:0,r.stage===0?2:3),.9+r.stage*.4,r.stage===1&&r.kind==='relay'?'water':'land',n);if(r.kind==='defense')for(const u of s.battle.team)u.hp=r.hp[u.id]?Math.max(1,Math.floor(u.maxHp*r.hp[u.id]/10000)):0;}
function finishRun(s,d,complete){const r=s.expansion.run,f=complete?1:.5;affairReward(s,{silver:Math.floor(r.loot.silver*f),items:{...(r.loot.iron?{iron:Math.floor(r.loot.iron*f)}:{}),...(complete?{material_choice:1}: {})}},d);if(complete)count(s,'venture_win_'+r.kind);journal(s,'【战役收队】'+(complete?'完成三场，全额结算并获得军需自选箱 1。':'提前结束，带回已暂存物资的一半；已有兵损和消耗保留。'));s.expansion.run=null;}
export function finishExpansion(s,b,d){if(!s.expansion||b.guest)return;const x=s.expansion;if(b.outcome==='victory'){for(const [id,m]of Object.entries(COMBOS))if(m.team.every(id=>b.team.some(u=>u.id===id)))x.combos[id]=Math.min(3,(x.combos[id]||0)+1);}
 if(b.context.type!=='realm')return;if(b.context.kind==='personal'){const id=b.context.id,ok=b.outcome==='victory'&&(id==='huarong'?b.elapsed<=60000:b.team.every(u=>u.hp>0));if(ok&&!x.personal[id]){x.personal[id]=true;grant(s,{items:{[id+'_manual']:2,spirit_essence:2}},d);journal(s,'【专属任务完成】'+PERSONAL[id].name+'；本领已强化。');}else journal(s,'【专属任务】未满足额外目标，下次可以重新挑战。');return;}
 if(!['defense','relay'].includes(b.context.kind))return;const r=x.run;requireRule(r&&r.kind===b.context.kind&&r.stage+1===b.context.tier,'战役场次不匹配。');if(b.outcome!=='victory'){finishRun(s,d,false);return;}r.loot.silver+=100;r.loot.iron+=2;if(r.kind==='defense')for(const u of b.team)r.hp[u.id]=u.hp?Math.min(10000,Math.floor(u.hp/u.maxHp*10000)+(r.layout==='reserve'?1000:0)):0;r.stage++;journal(s,'【战役推进】已完成 '+r.stage+' / 3 场，战利品暂存。');}
export function diplomacyAction(s,d,a){const x=expansion(s),id=a.id,choice=a.choice;requireRule(s.realm&&['yuncheng','jingyang','dongxi'].includes(id)&&['merchants','villages','river'].includes(choice),'请选择有效的地区与支持对象。');const key=id+'_'+s.daily.date.slice(0,7);requireRule(!x.diplomacy[key],'本月此地的抉择已经作出。');requireRule(s.camp.buildings.hall>=({yuncheng:1,jingyang:2,dongxi:3})[id],'寨子规模不足。');if(choice==='merchants'){requireRule(s.player.silver>=100,'需要碎银 100。');s.player.silver-=100;s.camp.food=Math.min(10000000,s.camp.food+60);}if(choice==='villages'){requireRule(s.camp.food>=40,'需要粮草 40。');s.camp.food-=40;grant(s,{items:{herb:5}},d);}if(choice==='river'){requireRule(s.camp.wood>=30,'需要木材 30。');s.camp.wood-=30;grant(s,{items:{cloth:3}},d);}for(const k of Object.keys(s.realm.relations))s.realm.relations[k]=Math.max(0,Math.min(100,s.realm.relations[k]+(k===choice?12:-4)));x.diplomacy[key]=choice;journal(s,'【势力抉择】支持者关系 +12，其余两方 −4。本月不能改选。');}
