import { frontierMap } from './frontier-ui.js?v=0.15.0';
import { enemyIntel } from './martial-ui.js?v=0.15.0';
import { routeTo, routeBarriers, conditionText, LOCAL_BENEFITS } from './world-map.js?v=0.15.0';
export function worldMap(s,d,target,esc,btn){
  const selected=d.by.maps[target]||d.by.maps[s.location],path=routeTo(s,d,selected.id),preview=path||routeTo(s,d,selected.id,true),barriers=path?[]:routeBarriers(s,d,preview),regions=[...new Set(d.maps.map(m=>m.region))];
  const feature=m=>[...(LOCAL_BENEFITS[m.id]?[LOCAL_BENEFITS[m.id].name+' · 每日一次']:[]),...m.dungeons.map(id=>'副本：'+d.by.dungeons[id].name),...d.heroes.filter(h=>h.meetMap===m.id).map(h=>'可遇：'+h.name)].join(' · ')||'人物往事与江湖寻访';
  return `${s.frontier?'<nav class="frontier-shortcuts" aria-label="地图分区"><a href="#frontier-map">领地据点</a><a href="#atlas-title">江湖地点全图</a></nav>':''}${frontierMap(s,d,esc,btn)}<section class="world-atlas" aria-labelledby="atlas-title"><div class="atlas-heading"><div><p class="kicker">江湖全图 · ${d.maps.length} 处去处</p><h1 id="atlas-title">山川有路，去处先知</h1></div><span class="badge">所在：${esc(d.by.maps[s.location].name)}</span></div><p class="note">所有地点与相连道路均已标出。选择地点可看完整行程；尚未开放的路线会列出条件。</p>
    <section id="atlas-target" class="atlas-target" aria-live="polite"><div class="goal-heading"><h2>${esc(selected.name)}</h2><span>${selected.id===s.location?'身在此处':path?'可以前往':'路线待开放'}</span></div><p>${esc(selected.description)}</p><p class="atlas-route">行程：${[s.location,...(preview||[])].map(id=>esc(d.by.maps[id].name)).join(' → ')}</p>${barriers.length?`<ul class="atlas-locks">${barriers.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>`:''}<p class="note">${esc(feature(selected))}</p>${selected.dungeons.map(id=>{const x=d.by.dungeons[id];return `<details class="map-enemy-preview"><summary>${esc(x.name)} · 敌情与消耗</summary><p class="note">体力 ${x.cost} · 英雄 ${x.level} 级 · 每日 ${x.limit} 次</p>${x.kind==='scheme'?'<p>计策历练，无直接交战。</p>':enemyIntel(s,d,x.enemy,x.scale)}</details>`;}).join('')}${LOCAL_BENEFITS[selected.id]?`<p class="note">${esc(LOCAL_BENEFITS[selected.id].description)}</p>`:''}${selected.id!==s.location?btn(path?'沿路前往 · '+path.length+' 段路':'条件不足，暂不可前往',{type:'travel',id:selected.id},'primary',!path):'<button type="button" class="secondary" data-map-local>查看此地事务</button>'}${path?.length?'<p class="note">每段路经过半个时辰；沿途不会自动开始剧情或领取物品。</p>':''}</section>
    <nav class="atlas-regions" aria-label="地图区域">${regions.map((r,i)=>`<button type="button" data-map-region="${i}">${esc(r)}</button>`).join('')}</nav>
    <div class="atlas-chart">${regions.map((r,i)=>`<section class="atlas-region" id="map-region-${i}"><h2>${esc(r)}</h2><div class="atlas-nodes">${d.maps.filter(m=>m.region===r).map(m=>`<article class="atlas-node ${m.id===s.location?'node-current':''} ${m.id===selected.id?'node-selected':''}"><button type="button" class="atlas-place" data-command="${esc(JSON.stringify({type:'ui_mapInspect',id:m.id}))}" aria-pressed="${m.id===selected.id}"><b>${esc(m.name)}</b><span>${m.id===s.location?'当前所在':s.progress.visited.includes(m.id)?'曾经到访':'尚未到访'}</span></button><p class="atlas-exits">${m.links.map(l=>`<span>→ ${esc(d.by.maps[l.target].name)}${l.condition?` <small>〔${esc(conditionText(l.condition,d))}〕</small>`:''}</span>`).join('')}</p><p class="atlas-feature">${esc(feature(m))}</p></article>`).join('')}</div></section>`).join('')}</div></section>`;
}
export function localBenefit(s,btn){const b=LOCAL_BENEFITS[s.location];if(!b)return '';const claimed=!!s.daily.counters['visit_bonus_'+s.location];return `<section class="local-benefit"><h2>此地额外好处 · ${b.name}</h2><p>${b.description}</p><p class="note">每日可领取一次；招募、打造、采买和领骑可直接使用各自功能入口。</p>${btn(claimed?'今日酬谢已领':'领取探访酬谢',{type:'localBenefit'},'secondary',claimed)}</section>`;}
